# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7"

  config.vm.provider "virtualbox" do |v|
    # VBoxManage setextradata "simple_default_xxx" "VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled" 1
    v.customize ["setextradata", :id, "VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled", "1"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum install -y epel-release
    yum install -y https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm
    yum install -y icinga2

    cp /vagrant/config/downtimes.conf /etc/icinga2/conf.d/downtimes.conf

    timedatectl set-local-rtc 0
    timedatectl set-ntp 0

    icinga2 daemon -C
  SHELL
end
